In [2]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(suppress=True)

# Input Parameters

In [3]:
rays    = 2
velo    = np.array([1800,1500])
dz      = np.array([900, 600])
layers  = len(velo)
wave    = 1

In [5]:
theta = np.empty(shape = [0, rays])
for i in range(1, rays+1):
    t = i * 10
    theta = np.array([np.append(theta, t)])
# print(theta)

# Ray Parameter

In [35]:
p = np.empty(shape = [0, rays])
for i in range(rays):
    x = np.sin(np.deg2rad(theta[0, i])) / velo[i]
    p = np.array([np.append(p, x)])
print("p = \n", p)

pz = np.empty(shape = [layers, rays])
for j in range(rays):
    for i in range(layers):
        pz[i, j] = np.sqrt((1/(velo[i]))**(2) - (p[0, j])**2)
print("pz = \n", pz)

p = 
 [[0.00009647 0.00022801]]
pz = 
 [[0.00054712 0.00050661]
 [0.00065965 0.00062646]]


# Lateral Displacement

In [36]:
dx = np.empty(shape = [layers, rays])
for j in range(rays):
    for i in range(layers):
        dx[i, j] = p[0, j] * dz[i]/ pz[i, j]
print(dx)

[[158.69428264 405.07061017]
 [ 87.74767021 218.38214056]]
